<template><div><h1 id="格式-manifest文件" tabindex="-1"><a class="header-anchor" href="#格式-manifest文件" aria-hidden="true">#</a> 格式：Manifest文件</h1>
<h2 id="字段说明" tabindex="-1"><a class="header-anchor" href="#字段说明" aria-hidden="true">#</a> 字段说明</h2>
<p>下面的JSON示例了manifest支持的字段，每个字段都有连接指向专有的说明。必须的字段只有：name和version。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token punctuation">{</span>
<span class="token comment">// 必须的字段</span>
  <span class="token string-property property">"name"</span><span class="token operator">:</span> <span class="token string">"My Extension"</span><span class="token punctuation">,</span>
  <span class="token string-property property">"version"</span><span class="token operator">:</span> <span class="token string">"versionString"</span><span class="token punctuation">,</span>
  <span class="token string-property property">"manifest_version"</span><span class="token operator">:</span> <span class="token number">2</span><span class="token punctuation">,</span>
  <span class="token comment">// 建议提供的字段</span>
  <span class="token string-property property">"description"</span><span class="token operator">:</span> <span class="token string">"A plain text description"</span><span class="token punctuation">,</span>
  <span class="token string-property property">"icons"</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token operator">...</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token string-property property">"default_locale"</span><span class="token operator">:</span> <span class="token string">"en"</span><span class="token punctuation">,</span>
  <span class="token comment">// 多选一，或者都不提供</span>
  <span class="token string-property property">"browser_action"</span><span class="token operator">:</span> <span class="token punctuation">{</span><span class="token operator">...</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token string-property property">"page_action"</span><span class="token operator">:</span> <span class="token punctuation">{</span><span class="token operator">...</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token string-property property">"theme"</span><span class="token operator">:</span> <span class="token punctuation">{</span><span class="token operator">...</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token string-property property">"app"</span><span class="token operator">:</span> <span class="token punctuation">{</span><span class="token operator">...</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token comment">// 根据需要提供</span>
  <span class="token string-property property">"background"</span><span class="token operator">:</span> <span class="token punctuation">{</span><span class="token operator">...</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token string-property property">"chrome_url_overrides"</span><span class="token operator">:</span> <span class="token punctuation">{</span><span class="token operator">...</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token string-property property">"content_scripts"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token operator">...</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
  <span class="token string-property property">"content_security_policy"</span><span class="token operator">:</span> <span class="token string">"policyString"</span><span class="token punctuation">,</span>
  <span class="token string-property property">"file_browser_handlers"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token operator">...</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
  <span class="token string-property property">"homepage_url"</span><span class="token operator">:</span> <span class="token string">"http://path/to/homepage"</span><span class="token punctuation">,</span>
  <span class="token string-property property">"incognito"</span><span class="token operator">:</span> <span class="token string">"spanning"</span> or <span class="token string">"split"</span><span class="token punctuation">,</span>
  <span class="token string-property property">"intents"</span><span class="token operator">:</span> <span class="token punctuation">{</span><span class="token operator">...</span><span class="token punctuation">}</span>
  <span class="token string-property property">"key"</span><span class="token operator">:</span> <span class="token string">"publicKey"</span><span class="token punctuation">,</span>
  <span class="token string-property property">"minimum_chrome_version"</span><span class="token operator">:</span> <span class="token string">"versionString"</span><span class="token punctuation">,</span>
  <span class="token string-property property">"nacl_modules"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token operator">...</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
  <span class="token string-property property">"offline_enabled"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
  <span class="token string-property property">"omnibox"</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token string-property property">"keyword"</span><span class="token operator">:</span> <span class="token string">"aString"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token string-property property">"options_page"</span><span class="token operator">:</span> <span class="token string">"aFile.html"</span><span class="token punctuation">,</span>
  <span class="token string-property property">"permissions"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token operator">...</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
  <span class="token string-property property">"plugins"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token operator">...</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
  <span class="token string-property property">"requirements"</span><span class="token operator">:</span> <span class="token punctuation">{</span><span class="token operator">...</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token string-property property">"update_url"</span><span class="token operator">:</span> <span class="token string">"http://path/to/updateInfo.xml"</span><span class="token punctuation">,</span>
  <span class="token string-property property">"web_accessible_resources"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token operator">...</span><span class="token punctuation">]</span>
<span class="token punctuation">}</span>  
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="字段的含义" tabindex="-1"><a class="header-anchor" href="#字段的含义" aria-hidden="true">#</a> 字段的含义</h2>
<p>部分字段的详细的含义如下：</p>
<h3 id="app" tabindex="-1"><a class="header-anchor" href="#app" aria-hidden="true">#</a> app</h3>
<p>可安装的webapp，包括打包过的app，需要这个字段来指定app需要使用的url。最重要的是app的启动页面------当用户在点击app的图标后，浏览器将导航到的地方。</p>
<p>更详细的信息，请参考文档<a href="http://chrome.cenchy.com/developers_guide.html" target="_blank" rel="noopener noreferrer">hosted apps<ExternalLinkIcon/></a>和<a href="http://code.google.com/chrome/extensions/apps.html" target="_blank" rel="noopener noreferrer">packaged apps<ExternalLinkIcon/></a>.：</p>
<h3 id="default-locale" tabindex="-1"><a class="header-anchor" href="#default-locale" aria-hidden="true">#</a> default_locale</h3>
<p>指定这个扩展保的缺省字符串的子目录：_lcoales。如果扩展有_locales目录，这个字段是必须的。如果没有_locales目录，这个字段是必须不存在的。具体见<a href="http://chrome.cenchy.com/i18n.html" target="_blank" rel="noopener noreferrer">Internationalization<ExternalLinkIcon/></a>.。</p>
<h3 id="description" tabindex="-1"><a class="header-anchor" href="#description" aria-hidden="true">#</a> description</h3>
<p>描述扩种的一段字符串（不能是html或者其他格式，不能超过132个字符）。这个描述必须对浏览器扩展的管理界面和<a href="https://chrome.google.com/webstore" target="_blank" rel="noopener noreferrer">Chrome Web Store<ExternalLinkIcon/></a>都合适。你可以指定本地相关的字符串，具体参考:<a href="http://chrome.cenchy.com/i18n.html" target="_blank" rel="noopener noreferrer">Internationalization<ExternalLinkIcon/></a>。</p>
<h3 id="homepage-url" tabindex="-1"><a class="header-anchor" href="#homepage-url" aria-hidden="true">#</a> homepage_url</h3>
<p>这个扩展的主页 url。扩展的管理界面里面将有一个链接指向这个url。<a href="http://chrome.cenchy.com/hosting.html" target="_blank" rel="noopener noreferrer">如果你将扩展放在自己的网站上<ExternalLinkIcon/></a>，这个url就很有用了。如果你通过了<a href="https://chrome.google.com/extensions" target="_blank" rel="noopener noreferrer">Extensions Gallery<ExternalLinkIcon/></a>和<a href="https://chrome.google.com/webstore" target="_blank" rel="noopener noreferrer">Chrome Web Store<ExternalLinkIcon/></a>来分发扩展，主页 缺省就是扩展的页面。</p>
<h3 id="icons" tabindex="-1"><a class="header-anchor" href="#icons" aria-hidden="true">#</a> icons</h3>
<p>一个或者多个图标来表示扩展，app，和皮肤。你通常可以提供一个128x128的图标，这个图标将在webstore安装时候使用。扩展需要一个48x48的图标，扩展管理页面需要这个图标。同时，你还可以提供给一个16x16的图标作为扩页面的fa网页图标 。这个16x16的图标，还将显示在实验性的扩展<a href="http://code.google.com/chrome/extensions/experimental.infobars.html" target="_blank" rel="noopener noreferrer">infobar<ExternalLinkIcon/></a>特性上。</p>
<p>图标要求是png格式，因为png格式是对透明支持最好的。你也可以用其他webkit支持的格式，如BMP,GIF,ICON和JPEG。下面有个例子：</p>
</div></template>
